from .company_change_page import *
from .login_page import *
from .recovery_page import *
from .notdone_page import *
from .main_menu_page import *
from .person_page import *
from .project_page import *
from .edit_event_page import *
from .requests_page import *
from .create_request_page import *
from .new_request_page import *
from .ppl_approval_page import *
from .ppl_approval_card_page import *
from .prj_approval_page import *
from .prj_approval_card_page import *
from .portfolio_page import *
from .worksheet_page import *
from .create_event_page import *
from .event_page import *
from .calendar_page import *
from .create_task_page import *
from .push_page import *